"""empty message

Revision ID: 92705970b0df
Revises: ea0d19c28e8f
Create Date: 2023-09-24 16:43:05.837053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92705970b0df'
down_revision = 'ea0d19c28e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
